CREATE DATABASE erp
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

SELECT current_database();



CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    temporary_password TEXT,
    profile_image TEXT, -- stores avatar path like /uploads/abc.png
    role VARCHAR(50) NOT NULL DEFAULT 'user',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO users 
(full_name, email, password_hash, role)
VALUES 
('Admin User', 'admin@example.com', '123456', 'admin');
--Employees Table query
BEGIN;

CREATE TABLE IF NOT EXISTS employees (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone VARCHAR(20),
  date_of_birth TIMESTAMP WITH TIME ZONE,
  gender VARCHAR(10) CHECK (gender IN ('male', 'female', 'other')),
  address TEXT,
  city VARCHAR(100),
  state VARCHAR(100),
  zip_code VARCHAR(10),
  department VARCHAR(100) NOT NULL,
  designation VARCHAR(100) NOT NULL,
  leave_balances JSONB NOT NULL DEFAULT '{}'::jsonb,
  shift_id INTEGER,
  manager_id INTEGER,
  join_date TIMESTAMP WITH TIME ZONE NOT NULL,
  employment_type VARCHAR(20) NOT NULL DEFAULT 'full_time'
    CHECK (employment_type IN ('full_time', 'part_time', 'contract', 'intern')),
  base_salary NUMERIC(12,2),
  employee_code VARCHAR(50) NOT NULL,
  profile_image TEXT, -- stores avatar file path
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS employee_documents (
id SERIAL PRIMARY KEY,
employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
document_type VARCHAR(50) NOT NULL
CHECK (document_type IN ('resume', 'id_proof', 'address_proof', 'educational_certificate', 'other')),
document_name VARCHAR(255) NOT NULL,
file_path TEXT NOT NULL,
file_size INTEGER,
mime_type VARCHAR(100),
uploaded_by INTEGER NOT NULL,
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_employees_is_active ON employees(is_active);
CREATE INDEX IF NOT EXISTS idx_employee_documents_employee_id ON employee_documents(employee_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_employees_email_active
ON employees (lower(email))
WHERE is_active = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_employees_code_active
ON employees (employee_code)
WHERE is_active = TRUE;

COMMIT;


--Departments
CREATE TABLE IF NOT EXISTS departments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  description TEXT,
  parent_department_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

--Designation
CREATE TABLE IF NOT EXISTS designations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id INTEGER NOT NULL,
  title VARCHAR(120) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_designations_department
    FOREIGN KEY (department_id)
    REFERENCES departments (id),
  CONSTRAINT uq_designations_department_title
    UNIQUE (department_id, title)
);


--Departments head
CREATE TABLE IF NOT EXISTS department_heads (
  id SERIAL PRIMARY KEY,
  department_id INTEGER NOT NULL UNIQUE,
  employee_id INTEGER NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_department_heads_department
    FOREIGN KEY (department_id) REFERENCES departments(id),
  CONSTRAINT fk_department_heads_employee
    FOREIGN KEY (employee_id) REFERENCES employees(id)
);

--Attendence Table
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attendance_status_enum') THEN
    CREATE TYPE attendance_status_enum AS ENUM (
      'present',
      'late',
      'absent',
      'half_day',
      'on_leave'
    );
  END IF;
END $$;

-- Recruitment: Current Openings and Candidates
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'current_opening_status_enum') THEN
    CREATE TYPE current_opening_status_enum AS ENUM ('Open', 'Interview', 'Closed');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'role_type_enum') THEN
    CREATE TYPE role_type_enum AS ENUM ('Internship', 'Full-time Job', 'Part-time Job', 'Contract');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'salary_type_enum') THEN
    CREATE TYPE salary_type_enum AS ENUM ('Paid', 'Unpaid');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS current_openings (
  id SERIAL PRIMARY KEY,
  role VARCHAR(160) NOT NULL,
  title VARCHAR(200) NOT NULL,
  department VARCHAR(120),
  location VARCHAR(120) NOT NULL,
  role_type role_type_enum NOT NULL,
  salary_type salary_type_enum NOT NULL,
  no_of_positions INTEGER NOT NULL DEFAULT 1,
  description TEXT,
  requirements TEXT,
  experience_required VARCHAR(100),
  skills TEXT,
  date_published TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  deadline TIMESTAMP WITH TIME ZONE,
  status current_opening_status_enum NOT NULL DEFAULT 'Open',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_deadline_future CHECK (deadline IS NULL OR deadline > NOW()),
  CONSTRAINT chk_no_of_positions_positive CHECK (no_of_positions > 0)
);

CREATE INDEX IF NOT EXISTS idx_current_openings_is_active ON current_openings(is_active);
CREATE INDEX IF NOT EXISTS idx_current_openings_status ON current_openings(status);
CREATE INDEX IF NOT EXISTS idx_current_openings_role_type ON current_openings(role_type);
CREATE INDEX IF NOT EXISTS idx_current_openings_salary_type ON current_openings(salary_type);
CREATE INDEX IF NOT EXISTS idx_current_openings_deadline ON current_openings(deadline);
CREATE INDEX IF NOT EXISTS idx_current_openings_date_published ON current_openings(date_published);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'candidate_stage_enum') THEN
    CREATE TYPE candidate_stage_enum AS ENUM (
      'Applied',
      'Screening',
      'Interview',
      'Offer',
      'Onboarding',
      'Hired',
      'Rejected'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS candidates (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(160) NOT NULL,
  email VARCHAR(160) NOT NULL,
  phone VARCHAR(30),
  current_opening_id INTEGER NOT NULL REFERENCES current_openings(id),
  experience_years NUMERIC(4,1),
  score INTEGER NOT NULL DEFAULT 0,
  stage candidate_stage_enum NOT NULL DEFAULT 'Applied',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_candidates_opening_id ON candidates(current_opening_id);
CREATE INDEX IF NOT EXISTS idx_candidates_stage ON candidates(stage);
CREATE INDEX IF NOT EXISTS idx_candidates_is_active ON candidates(is_active);
CREATE UNIQUE INDEX IF NOT EXISTS uq_candidates_email_opening_active
  ON candidates (lower(email), current_opening_id)
  WHERE is_active = TRUE;

CREATE TABLE IF NOT EXISTS attendance_records (
  id SERIAL PRIMARY KEY,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  attendance_date DATE NOT NULL,
  status attendance_status_enum NOT NULL,
  check_in_time TIME,
  check_out_time TIME,
  worked_minutes INTEGER,
  overtime_minutes INTEGER NOT NULL DEFAULT 0,
  remarks TEXT,
  marked_by INTEGER NOT NULL REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT attendance_records_employee_date_unique UNIQUE (employee_id, attendance_date)
);

CREATE INDEX IF NOT EXISTS idx_attendance_records_date ON attendance_records(attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_records_status ON attendance_records(status);

-- Shift management tables
CREATE TABLE IF NOT EXISTS shifts (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  break_minutes INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Leave Types
CREATE TABLE IF NOT EXISTS leave_types (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  abbreviation VARCHAR(12) NOT NULL,
  days_per_year INTEGER,
  carry_forward BOOLEAN NOT NULL DEFAULT FALSE,
  encashable BOOLEAN NOT NULL DEFAULT FALSE,
  applicable_to VARCHAR(150) NOT NULL DEFAULT 'All Employees',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leave_types_is_active ON leave_types(is_active);

-- Leaves
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'leave_status_enum') THEN
    CREATE TYPE leave_status_enum AS ENUM ('pending', 'approved', 'rejected');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS leaves (
  id SERIAL PRIMARY KEY,
  leave_code VARCHAR(40) NOT NULL UNIQUE,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  leave_type_id INTEGER NOT NULL REFERENCES leave_types(id),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  total_days INTEGER NOT NULL,
  reason TEXT NOT NULL,
  attachment_name VARCHAR(255),
  status leave_status_enum NOT NULL DEFAULT 'pending',
  created_by INTEGER REFERENCES users(id),
  reviewed_by INTEGER REFERENCES users(id),
  reviewed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leaves_employee_id ON leaves(employee_id);
CREATE INDEX IF NOT EXISTS idx_leaves_leave_type_id ON leaves(leave_type_id);
CREATE INDEX IF NOT EXISTS idx_leaves_status ON leaves(status);

-- Employee -> Shift relationship
CREATE INDEX IF NOT EXISTS idx_employees_shift_id ON employees(shift_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_employees_shift'
  ) THEN
    ALTER TABLE employees
      ADD CONSTRAINT fk_employees_shift
      FOREIGN KEY (shift_id)
      REFERENCES shifts(id)
      ON DELETE SET NULL;
  END IF;
END $$;


----Job Application table
DO $$
BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_applications_status_enum') THEN
CREATE TYPE job_applications_status_enum AS ENUM ('Submitted', 'Reviewed', 'Shortlisted', 'Rejected', 'Hired');
END IF;
END$$;

CREATE TABLE IF NOT EXISTS job_applications (
id SERIAL PRIMARY KEY,
current_opening_id INTEGER NOT NULL REFERENCES current_openings(id),
full_name VARCHAR(160) NOT NULL,
email VARCHAR(160) NOT NULL,
phone VARCHAR(30),
cv_file_url VARCHAR(300) NOT NULL,
cover_letter TEXT,
experience_years NUMERIC(4,1),
education_entries JSONB NOT NULL DEFAULT '[]'::jsonb,
experience_entries JSONB NOT NULL DEFAULT '[]'::jsonb,
status job_applications_status_enum NOT NULL DEFAULT 'Submitted',
is_active BOOLEAN NOT NULL DEFAULT TRUE,
created_at TIMESTAMPTZ DEFAULT NOW(),
updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_job_applications_opening ON job_applications(current_opening_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_email ON job_applications(email);
CREATE INDEX IF NOT EXISTS idx_job_applications_status ON job_applications(status);
CREATE INDEX IF NOT EXISTS idx_job_applications_is_active ON job_applications(is_active);

CREATE UNIQUE INDEX IF NOT EXISTS uq_job_applications_email_opening
ON job_applications(email, current_opening_id);


-------recruitment workflows------------
DO $$
BEGIN
  CREATE TYPE recruitment_workflows_offer_decision AS ENUM ('pending', 'accepted', 'rejected');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE recruitment_workflows_onboarding_decision AS ENUM ('pending', 'accepted', 'rejected');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS recruitment_workflows (
  id SERIAL PRIMARY KEY,
  candidate_id INTEGER NOT NULL UNIQUE REFERENCES candidates(id),
  job_application_id INTEGER NOT NULL UNIQUE REFERENCES job_applications(id),
  current_opening_id INTEGER NOT NULL REFERENCES current_openings(id),
  email VARCHAR(160) NOT NULL,
  interview_slots JSONB NOT NULL DEFAULT '[]'::jsonb,
  selected_slot_index INTEGER,
  selected_interview_slot JSONB,
  offer_letter_url TEXT,
  onboarding_package_url TEXT,
  onboarding_notes TEXT,
  hr_rejection_reason TEXT,
  candidate_rejection_reason TEXT,
  offer_decision recruitment_workflows_offer_decision NOT NULL DEFAULT 'pending',
  onboarding_decision recruitment_workflows_onboarding_decision NOT NULL DEFAULT 'pending',
  ats_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS recruitment_workflows_candidate_id_idx
  ON recruitment_workflows (candidate_id);

CREATE INDEX IF NOT EXISTS recruitment_workflows_job_application_id_idx
  ON recruitment_workflows (job_application_id);

CREATE INDEX IF NOT EXISTS recruitment_workflows_current_opening_id_idx
  ON recruitment_workflows (current_opening_id);

CREATE INDEX IF NOT EXISTS recruitment_workflows_email_idx
  ON recruitment_workflows (email);


  --Exit Requests

CREATE TYPE exit_type_enum AS ENUM ('resignation', 'termination');
CREATE TYPE exit_status_enum AS ENUM ('pending', 'approved', 'rejected', 'withdrawn');
CREATE TYPE exit_workflow_stage_enum AS ENUM ('resignations', 'approvals', 'clearance', 'f_and_f', 'exit_interviews', 'completed');
CREATE TYPE exit_step_status_enum AS ENUM ('pending', 'in_progress', 'completed');
CREATE TYPE exit_interview_status_enum AS ENUM ('pending', 'scheduled', 'done', 'waived');

CREATE TABLE exit_requests (
    id SERIAL PRIMARY KEY,
    exit_code VARCHAR(60) NOT NULL UNIQUE,
    employee_id INTEGER NOT NULL REFERENCES employees(id),
    exit_type exit_type_enum NOT NULL DEFAULT 'resignation',
    reason TEXT NOT NULL,
    attachment_name VARCHAR(255),
    last_working_date DATE NOT NULL,
    status exit_status_enum NOT NULL DEFAULT 'pending',
    workflow_stage exit_workflow_stage_enum NOT NULL DEFAULT 'resignations',
    clearance_status exit_step_status_enum NOT NULL DEFAULT 'pending',
    fnf_status exit_step_status_enum NOT NULL DEFAULT 'pending',
    interview_status exit_interview_status_enum NOT NULL DEFAULT 'pending',
    decision_notes TEXT,
    hr_notes TEXT,
    reviewed_by INTEGER,
    reviewed_at TIMESTAMP NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);


-- ==========================================
-- Payroll Management Tables
-- ==========================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'salary_component_type_enum') THEN
    CREATE TYPE salary_component_type_enum AS ENUM ('earning', 'deduction');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'salary_value_type_enum') THEN
    CREATE TYPE salary_value_type_enum AS ENUM ('fixed', 'percentage');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'salary_percentage_of_enum') THEN
    CREATE TYPE salary_percentage_of_enum AS ENUM ('base_salary', 'gross_pay');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payroll_run_status_enum') THEN
    CREATE TYPE payroll_run_status_enum AS ENUM ('draft', 'processing', 'approved', 'published');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payslip_status_enum') THEN
    CREATE TYPE payslip_status_enum AS ENUM ('generated', 'approved', 'paid');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payroll_rule_category_enum') THEN
    CREATE TYPE payroll_rule_category_enum AS ENUM ('salary', 'leave', 'overtime', 'cycle');
  END IF;
END $$;

-- Salary components (Earning/Deduction masters)
CREATE TABLE IF NOT EXISTS salary_components (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  component_type salary_component_type_enum NOT NULL,
  value_type salary_value_type_enum NOT NULL DEFAULT 'fixed',
  value NUMERIC(12,2) NOT NULL DEFAULT 0,
  percentage_of salary_percentage_of_enum NOT NULL DEFAULT 'base_salary',
  is_taxable BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Employee salary structure (one active structure per employee)
CREATE TABLE IF NOT EXISTS employee_salary_structures (
  id SERIAL PRIMARY KEY,
  employee_id INTEGER NOT NULL UNIQUE REFERENCES employees(id) ON DELETE CASCADE,
  annual_ctc NUMERIC(12,2),
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Payroll run tracking (one run per month-year)
CREATE TABLE IF NOT EXISTS payroll_runs (
  id SERIAL PRIMARY KEY,
  month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
  year INTEGER NOT NULL CHECK (year BETWEEN 2000 AND 2100),
  status payroll_run_status_enum NOT NULL DEFAULT 'draft',
  current_step INTEGER NOT NULL DEFAULT 1 CHECK (current_step BETWEEN 1 AND 5),
  processed_at TIMESTAMP WITH TIME ZONE,
  published_at TIMESTAMP WITH TIME ZONE,
  initiated_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_payroll_runs_month_year UNIQUE (month, year)
);

-- Payslips generated per employee per month
CREATE TABLE IF NOT EXISTS payslips (
  id SERIAL PRIMARY KEY,
  payroll_run_id INTEGER NOT NULL REFERENCES payroll_runs(id) ON DELETE CASCADE,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  month_year VARCHAR(7) NOT NULL,
  base_salary NUMERIC(12,2) NOT NULL DEFAULT 0,
  payable_days NUMERIC(8,2) NOT NULL DEFAULT 0,
  working_days INTEGER NOT NULL DEFAULT 30,
  overtime_minutes INTEGER NOT NULL DEFAULT 0,
  gross_pay NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_deductions NUMERIC(12,2) NOT NULL DEFAULT 0,
  net_pay NUMERIC(12,2) NOT NULL DEFAULT 0,
  status payslip_status_enum NOT NULL DEFAULT 'generated',
  generated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_payslips_employee_month UNIQUE (employee_id, month_year)
);

-- Payslip line items (earnings and deductions details)
CREATE TABLE IF NOT EXISTS payslip_line_items (
  id SERIAL PRIMARY KEY,
  payslip_id INTEGER NOT NULL REFERENCES payslips(id) ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  item_type salary_component_type_enum NOT NULL,
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Payroll rules (global payroll settings that affect real calculations)
CREATE TABLE IF NOT EXISTS payroll_rules (
  id SERIAL PRIMARY KEY,
  rule_key VARCHAR(80) NOT NULL UNIQUE,
  label VARCHAR(120) NOT NULL,
  category payroll_rule_category_enum NOT NULL DEFAULT 'salary',
  value JSONB NOT NULL DEFAULT '{}'::jsonb,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Useful indexes
CREATE INDEX IF NOT EXISTS idx_salary_components_type ON salary_components(component_type);
CREATE INDEX IF NOT EXISTS idx_salary_components_active ON salary_components(is_active);

CREATE INDEX IF NOT EXISTS idx_employee_salary_structures_employee ON employee_salary_structures(employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_salary_structures_active ON employee_salary_structures(is_active);

CREATE INDEX IF NOT EXISTS idx_payroll_runs_status ON payroll_runs(status);
CREATE INDEX IF NOT EXISTS idx_payroll_runs_initiated_by ON payroll_runs(initiated_by);

CREATE INDEX IF NOT EXISTS idx_payslips_payroll_run_id ON payslips(payroll_run_id);
CREATE INDEX IF NOT EXISTS idx_payslips_month_year ON payslips(month_year);
CREATE INDEX IF NOT EXISTS idx_payslips_status ON payslips(status);

CREATE INDEX IF NOT EXISTS idx_payslip_line_items_payslip_id ON payslip_line_items(payslip_id);
CREATE INDEX IF NOT EXISTS idx_payroll_rules_category ON payroll_rules(category);


-- Seed default payroll rules
INSERT INTO payroll_rules (rule_key, label, category, value, description, is_active)
VALUES
  ('salary_basis', 'Salary Basis', 'salary', '{"mode":"fixed_30","options":["fixed_30","calendar_days"]}'::jsonb, 'Choose whether monthly salary uses fixed 30 days or actual calendar days.', TRUE),
  ('paid_leave_treatment', 'Paid Leave Treatment', 'leave', '{"mode":"paid","options":["paid","deduct"]}'::jsonb, 'Control whether approved paid leaves are paid or deducted.', TRUE),
  ('leave_deduction_rate', 'Leave Deduction Rate', 'leave', '{"rate":1}'::jsonb, 'Deduction multiplier for unpaid leave day calculation.', TRUE),
  ('overtime_multiplier', 'Overtime Multiplier', 'overtime', '{"multiplier":1.5}'::jsonb, 'Multiplier applied on overtime hourly rate.', TRUE),
  ('proration_mode', 'Proration Mode', 'salary', '{"mode":"daily","options":["daily","monthly"]}'::jsonb, 'Determines whether salary is prorated daily or treated as monthly fixed.', TRUE)
ON CONFLICT (rule_key) DO NOTHING;